package sgr

const (
	Reset     string = "\x1b[0m"
	Bold      string = "\x1b[1m"
	Faint     string = "\x1b[2m"
	Italic    string = "\x1b[3m"
	Underline string = "\x1b[4m"
	SlowBlink string = "\x1b[5m"
	FastBlink string = "\x1b[6m"
	Invert    string = "\x1b[7m"
	Conceal   string = "\x1b[8m"
	Strike    string = "\x1b[9m"

	DefaultFont      string = "\x1b[10m"
	AlternativeFont1 string = "\x1b[12m"
	AlternativeFont2 string = "\x1b[13m"
	AlternativeFont3 string = "\x1b[14m"
	AlternativeFont4 string = "\x1b[15m"
	AlternativeFont5 string = "\x1b[16m"
	AlternativeFont6 string = "\x1b[17m"
	AlternativeFont7 string = "\x1b[18m"
	AlternativeFont8 string = "\x1b[19m"

	Fraktur          string = "\x1b[20m"
	DoublyUnderlined string = "\x1b[21m"
	NotBold          string = "\x1b[21m"
	NormalIntensity  string = "\x1b[22m"
	NotItalic        string = "\x1b[23m"
	NotBlackletter   string = "\x1b[23m"
	NotUnderlined    string = "\x1b[24m"
	NotBlinking      string = "\x1b[25m"
	Monospace        string = "\x1b[26m"
	NotInverted      string = "\x1b[27m"
	Reveal           string = "\x1b[28m"
	NotStriked       string = "\x1b[29m"

	FgBlack   string = "\x1b[30m"
	FgRed     string = "\x1b[31m"
	FgGreen   string = "\x1b[32m"
	FgYellow  string = "\x1b[33m"
	FgBlue    string = "\x1b[34m"
	FgMagenta string = "\x1b[35m"
	FgCyan    string = "\x1b[36m"
	FgWhite   string = "\x1b[37m"
	// FgColor string = "\x1b[38m"
	FgDefault string = "\x1b[39m"

	BgBlack   string = "\x1b[40m"
	BgRed     string = "\x1b[41m"
	BgGreen   string = "\x1b[42m"
	BgYellow  string = "\x1b[43m"
	BgBlue    string = "\x1b[44m"
	BgMagenta string = "\x1b[45m"
	BgCyan    string = "\x1b[46m"
	BgWhite   string = "\x1b[47m"
	// BgColor string = "\x1b[48m"
	BgDefault string = "\x1b[49m"

	NotMonospace string = "\x1b[50m"
	Frame        string = "\x1b[51m"
	Encircle     string = "\x1b[52m"
	Overline     string = "\x1b[53m"
	NotFramed    string = "\x1b[54m"
	NotEncircled string = "\x1b[54m"
	NotOverlined string = "\x1b[55m"
	// UnderlineColor string = "\x1b[58m"
	DefaultUnderlineColor string = "\x1b[59m"

	IdeogreamUnderline      string = "\x1b[60m"
	IdeogramDoubleUnderline string = "\x1b[61m"
	IdeogramOverline        string = "\x1b[62m"
	IdeogramDoubleOverline  string = "\x1b[63m"
	IdeogramStress          string = "\x1b[64m"
	NoIdeogram              string = "\x1b[65m"

	Superscript    string = "\x1b[73m"
	Subscript      string = "\x1b[74m"
	NotSuperscript string = "\x1b[75m"
	NotSubscript   string = "\x1b[75m"

	FgHiBlack   string = "\x1b[90m"
	FgHiRed     string = "\x1b[91m"
	FgHiGreen   string = "\x1b[92m"
	FgHiYellow  string = "\x1b[93m"
	FgHiBlue    string = "\x1b[94m"
	FgHiMagenta string = "\x1b[95m"
	FgHiCyan    string = "\x1b[96m"
	FgHiWhite   string = "\x1b[97m"

	BgHiBlack   string = "\x1b[100"
	BgHiRed     string = "\x1b[101m"
	BgHiGreen   string = "\x1b[102m"
	BgHiYellow  string = "\x1b[103m"
	BgHiBlue    string = "\x1b[104m"
	BgHiMagenta string = "\x1b[105m"
	BgHiCyan    string = "\x1b[106m"
	BgHiWhite   string = "\x1b[107m"
)
